version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=mountainpeak.settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migration:
    build: .
    command: bash -c "python manage.py makemigrations --settings=mountainpeak.settings && python manage.py migrate --settings=mountainpeak.settings"
    volumes:
      - .:/code
    depends_on:
      - db